language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
script: yarn test
before_deploy: yarn add now
deploy:
  - provider: script
    script: yarn deploy-from-travis
    skip_cleanup: true
    on:
      master: true

after_script: yarn coveralls
